name: Update Archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          # Clear any existing files.  This just makes using wget easier as it would otherwise
          # append .1, .2, etc. to the filename instead of overwriting.
          rm -rf linux
          rm -rf win
          rm -rf source
          
          mkdir linux
          mkdir win
          mkdir source
      
          pushd linux
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/spam/spam_linux_32.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/shv/shv_linux32.rar
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/sibea/sibea_binary.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/hype/hype_linux_32.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/lotz_semo/semo_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/semo2/semo2_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/femo/femo_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/spea2/spea2_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/nsga2/nsga2_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/ecea/ecea_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/ibea/ibea_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/msops/msops_linux.tar.gz
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/epsmoea/epsmoea_linux.tar.gz
          popd
          
          pushd win
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/spam/spam_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/shv/shv_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/sibea/sibea_binary.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/hype/hype_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/lotz_semo/semo_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/semo2/semo2_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/femo/femo_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/spea2/spea2_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/nsga2/nsga2_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/ecea/ecea_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/ibea/ibea_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/msops/msops_win.zip
          wget http://sop.tik.ee.ethz.ch/pisa/selectors/epsmoea/epsmoea_win.tar.gz
          popd
          
          pushd source
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/spam/spam_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/shv/shv_c_source.rar
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/sibea/sibea_source.zip
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/hype/hype_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/lotz_semo/semo_c_source.tar
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/semo2/semo2_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/femo/femo_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/spea2/spea2_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/spea2/spea2_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/nsga2/nsga2_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/ecea/ecea_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/ibea/ibea_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/msops/msops_c_source.tar.gz
          wget https://sop.tik.ee.ethz.ch/pisa/selectors/epsmoea/epsmoea_c_source.tar.gz
          popd

      - uses: stefanzweifel/git-auto-commit-action@v4
